/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mastermindtema3;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author FP Informática
 */
public class Main extends javax.swing.JFrame {

    ImageIcon bolaVerde = new ImageIcon(getClass().getResource("imagenes/peg_0.png"));
    ImageIcon bolaNaranja = new ImageIcon(getClass().getResource("imagenes/peg_1.png"));
    ImageIcon bolaRoja = new ImageIcon(getClass().getResource("imagenes/peg_2.png"));
    ImageIcon bolaAmarilla = new ImageIcon(getClass().getResource("imagenes/peg_3.png"));
    ImageIcon bolaTurquesa = new ImageIcon(getClass().getResource("imagenes/peg_4.png"));
    ImageIcon bolaAzul = new ImageIcon(getClass().getResource("imagenes/peg_5.png"));
    ImageIcon bolaBlanca = new ImageIcon(getClass().getResource("imagenes/bolablanca.jpg"));
    
    final byte BOLA_VERDE = 0;
    final byte BOLA_NARANJA = 1;
    final byte BOLA_ROJO = 2;
    final byte BOLA_AMARILLO = 3;
    final byte BOLA_TURQUESA = 4;
    final byte BOLA_AZUL= 5;
    
    String combinacionSecreta = "";
    
    String combinacionIntroducida = "";
    
    int botonPulsado;
    
    Random generarCom = new Random();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        jButtonEmpezar.setEnabled(false);
        jButtonComprobar.setEnabled(false);
        jButtonBolaVerde.setEnabled(false);
        jButtonBolaNaranja.setEnabled(false);
        jButtonBolaRoja.setEnabled(false);
        jButtonBolaAmarilla.setEnabled(false);
        jButtonBolaTurquesa.setEnabled(false);
        jButtonBolaAzul.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonBolaVerde = new javax.swing.JButton();
        jButtonBolaNaranja = new javax.swing.JButton();
        jButtonBolaRoja = new javax.swing.JButton();
        jButtonBolaAmarilla = new javax.swing.JButton();
        jButtonBolaTurquesa = new javax.swing.JButton();
        jButtonBolaAzul = new javax.swing.JButton();
        jButtonEmpezar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonComprobar = new javax.swing.JButton();
        jComboBoxNiveles = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MasterMind");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/bolablanca.jpg"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonBolaVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/peg_0.png"))); // NOI18N
        jButtonBolaVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaVerdeActionPerformed(evt);
            }
        });

        jButtonBolaNaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/peg_1.png"))); // NOI18N
        jButtonBolaNaranja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaNaranjaActionPerformed(evt);
            }
        });

        jButtonBolaRoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/peg_2.png"))); // NOI18N
        jButtonBolaRoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaRojaActionPerformed(evt);
            }
        });

        jButtonBolaAmarilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/peg_3.png"))); // NOI18N
        jButtonBolaAmarilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaAmarillaActionPerformed(evt);
            }
        });

        jButtonBolaTurquesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/peg_4.png"))); // NOI18N
        jButtonBolaTurquesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaTurquesaActionPerformed(evt);
            }
        });

        jButtonBolaAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mastermindtema3/imagenes/peg_5.png"))); // NOI18N
        jButtonBolaAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBolaAzulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBolaVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBolaNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBolaRoja, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBolaAmarilla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBolaTurquesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBolaAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBolaAzul)
                    .addComponent(jButtonBolaTurquesa)
                    .addComponent(jButtonBolaNaranja)
                    .addComponent(jButtonBolaVerde)
                    .addComponent(jButtonBolaRoja)
                    .addComponent(jButtonBolaAmarilla))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonEmpezar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEmpezar.setText("Nueva partida");
        jButtonEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpezarActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonComprobar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonComprobar.setText("Comprobar fila");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        jComboBoxNiveles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBoxNiveles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nivel 1", "Nivel 2", "Nivel 3", "" }));
        jComboBoxNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNivelesActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("1- Escoge un nivel");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("Instrucciones");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("2- Crea nueva partida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jComboBoxNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jButtonEmpezar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonComprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonBolaVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaVerdeActionPerformed
        botonPulsado = BOLA_VERDE;
        //jTextArea1.append(String.valueOf(BOLA_VERDE));
        jButtonBolaVerde.setEnabled(false);
        combinacionIntroducida += BOLA_VERDE;
    }//GEN-LAST:event_jButtonBolaVerdeActionPerformed

    private void jButtonBolaNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaNaranjaActionPerformed
        botonPulsado = BOLA_NARANJA;
        //jTextArea1.append(String.valueOf(BOLA_NARANJA));
        jButtonBolaNaranja.setEnabled(false);
        combinacionIntroducida += BOLA_NARANJA;
    }//GEN-LAST:event_jButtonBolaNaranjaActionPerformed

    private void jButtonBolaRojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaRojaActionPerformed
        botonPulsado = BOLA_ROJO;
        //jTextArea1.append(String.valueOf(BOLA_ROJO));
        jButtonBolaRoja.setEnabled(false);
        combinacionIntroducida += BOLA_ROJO;
    }//GEN-LAST:event_jButtonBolaRojaActionPerformed

    private void jButtonBolaAmarillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaAmarillaActionPerformed
        botonPulsado = BOLA_AMARILLO;
        //jTextArea1.append(String.valueOf(BOLA_AMARILLO));
        jButtonBolaAmarilla.setEnabled(false);
        combinacionIntroducida += BOLA_AMARILLO;
    }//GEN-LAST:event_jButtonBolaAmarillaActionPerformed

    private void jButtonBolaAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaAzulActionPerformed
        botonPulsado = BOLA_AZUL;
        //jTextArea1.append(String.valueOf(BOLA_AZUL));
        jButtonBolaAzul.setEnabled(false);
        combinacionIntroducida += BOLA_AZUL;
    }//GEN-LAST:event_jButtonBolaAzulActionPerformed

    private void jButtonBolaTurquesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBolaTurquesaActionPerformed
        botonPulsado = BOLA_TURQUESA;
        //jTextArea1.append(String.valueOf(BOLA_TURQUESA));
        jButtonBolaTurquesa.setEnabled(false);
        combinacionIntroducida += BOLA_TURQUESA;
    }//GEN-LAST:event_jButtonBolaTurquesaActionPerformed

    private void jButtonEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpezarActionPerformed
        jButtonEmpezar.setEnabled(false);
        jButtonComprobar.setEnabled(true);
        
        combinacionSecreta = "";
        
        switch(jComboBoxNiveles.getSelectedIndex()+1){
            case 1:
                do{
                    char num = (char)(generarCom.nextInt(4)+'0');
                    if(combinacionSecreta.indexOf(num) == -1){
                        combinacionSecreta += num;
                    }
                }while(combinacionSecreta.length() <4);
                break;
            case 2:
                do{
                    char num = (char)(generarCom.nextInt(5)+'0');
                    if(combinacionSecreta.indexOf(num) == -1){
                        combinacionSecreta += num;
                    }
                }while(combinacionSecreta.length() <4);
                break;
            case 3:
                do{
                    char num = (char)(generarCom.nextInt(6)+'0');
                    if(combinacionSecreta.indexOf(num) == -1){
                        combinacionSecreta += num;
                    }
                }while(combinacionSecreta.length() <4);
                break;
        }
        
        jLabel1.setIcon(bolaBlanca);
        jLabel2.setIcon(bolaBlanca);
        jLabel3.setIcon(bolaBlanca);
        jLabel4.setIcon(bolaBlanca);
        jLabel5.setIcon(bolaBlanca);
        jLabel6.setIcon(bolaBlanca);
        jLabel7.setIcon(bolaBlanca);
        jLabel8.setIcon(bolaBlanca);
        jLabel9.setIcon(bolaBlanca);
        jLabel10.setIcon(bolaBlanca);
        jLabel11.setIcon(bolaBlanca);
        jLabel12.setIcon(bolaBlanca);
        jLabel13.setIcon(bolaBlanca);
        jLabel14.setIcon(bolaBlanca);
        jLabel15.setIcon(bolaBlanca);
        jLabel16.setIcon(bolaBlanca);
        jLabel17.setIcon(bolaBlanca);
        jLabel18.setIcon(bolaBlanca);
        jLabel19.setIcon(bolaBlanca);
        jLabel20.setIcon(bolaBlanca);
        jLabel21.setIcon(bolaBlanca);
        jLabel22.setIcon(bolaBlanca);
        jLabel23.setIcon(bolaBlanca);
        jLabel24.setIcon(bolaBlanca);
            
        
        System.out.println("La combinación secreta es: "+combinacionSecreta);
        
    }//GEN-LAST:event_jButtonEmpezarActionPerformed

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
        int iguales = 0;
        int distintos = 0;
        int incorrectos = 0;
        
        switch(jComboBoxNiveles.getSelectedIndex()+1){
            case 1:
                if (combinacionSecreta.equals(combinacionIntroducida)) {
                    JOptionPane.showMessageDialog(this, "¡¡HAS GANADO!!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    jButtonComprobar.setEnabled(false);
                    jButtonEmpezar.setEnabled(false);
                    jButtonBolaVerde.setEnabled(false);
                    jButtonBolaNaranja.setEnabled(false);
                    jButtonBolaRoja.setEnabled(false);
                    jButtonBolaAmarilla.setEnabled(false);
                    jButtonBolaTurquesa.setEnabled(false);
                    jButtonBolaAzul.setEnabled(false);
                    jLabel1.setIcon(bolaBlanca);
                    jLabel2.setIcon(bolaBlanca);
                    jLabel3.setIcon(bolaBlanca);
                    jLabel4.setIcon(bolaBlanca);
                    jLabel5.setIcon(bolaBlanca);
                    jLabel6.setIcon(bolaBlanca);
                    jLabel7.setIcon(bolaBlanca);
                    jLabel8.setIcon(bolaBlanca);
                    jLabel9.setIcon(bolaBlanca);
                    jLabel10.setIcon(bolaBlanca);
                    jLabel11.setIcon(bolaBlanca);
                    jLabel12.setIcon(bolaBlanca);
                    jLabel13.setIcon(bolaBlanca);
                    jLabel14.setIcon(bolaBlanca);
                    jLabel15.setIcon(bolaBlanca);
                    jLabel16.setIcon(bolaBlanca);
                    jLabel17.setIcon(bolaBlanca);
                    jLabel18.setIcon(bolaBlanca);
                    jLabel19.setIcon(bolaBlanca);
                    jLabel20.setIcon(bolaBlanca);
                    jLabel21.setIcon(bolaBlanca);
                    jLabel22.setIcon(bolaBlanca);
                    jLabel23.setIcon(bolaBlanca);
                    jLabel24.setIcon(bolaBlanca);
                }else{
                    for (int i = 0; i < 4; i++) {
                        char caracter = combinacionIntroducida.charAt(i);
                        int resultado = combinacionSecreta.indexOf(caracter);
                        if (resultado == -1) {
                            incorrectos++;
                        } else {
                            if (caracter == combinacionSecreta.charAt(i)) {
                                iguales++;
                            } else {
                                distintos++;
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Hay " + iguales + " bien colocadas, " + incorrectos + " incorrectas y " +distintos+ " mal colocadas" );
                    jButtonBolaVerde.setEnabled(true);
                    jButtonBolaNaranja.setEnabled(true);
                    jButtonBolaRoja.setEnabled(true);
                    jButtonBolaAmarilla.setEnabled(true);
                    jButtonBolaTurquesa.setEnabled(false);
                    jButtonBolaAzul.setEnabled(false);
                }
                break;
                
             case 2:
                if (combinacionSecreta.equals(combinacionIntroducida)) {
                    JOptionPane.showMessageDialog(this, "¡¡HAS GANADO!!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    jButtonComprobar.setEnabled(false);
                    jButtonEmpezar.setEnabled(false);
                    jButtonBolaVerde.setEnabled(false);
                    jButtonBolaNaranja.setEnabled(false);
                    jButtonBolaRoja.setEnabled(false);
                    jButtonBolaAmarilla.setEnabled(false);
                    jButtonBolaTurquesa.setEnabled(false);
                    jButtonBolaAzul.setEnabled(false);
                    jLabel1.setIcon(bolaBlanca);
                    jLabel2.setIcon(bolaBlanca);
                    jLabel3.setIcon(bolaBlanca);
                    jLabel4.setIcon(bolaBlanca);
                    jLabel5.setIcon(bolaBlanca);
                    jLabel6.setIcon(bolaBlanca);
                    jLabel7.setIcon(bolaBlanca);
                    jLabel8.setIcon(bolaBlanca);
                    jLabel9.setIcon(bolaBlanca);
                    jLabel10.setIcon(bolaBlanca);
                    jLabel11.setIcon(bolaBlanca);
                    jLabel12.setIcon(bolaBlanca);
                    jLabel13.setIcon(bolaBlanca);
                    jLabel14.setIcon(bolaBlanca);
                    jLabel15.setIcon(bolaBlanca);
                    jLabel16.setIcon(bolaBlanca);
                    jLabel17.setIcon(bolaBlanca);
                    jLabel18.setIcon(bolaBlanca);
                    jLabel19.setIcon(bolaBlanca);
                    jLabel20.setIcon(bolaBlanca);
                    jLabel21.setIcon(bolaBlanca);
                    jLabel22.setIcon(bolaBlanca);
                    jLabel23.setIcon(bolaBlanca);
                    jLabel24.setIcon(bolaBlanca);
                }else{
                    for (int i = 0; i < 4; i++) {
                        char caracter = combinacionIntroducida.charAt(i);
                        int resultado = combinacionSecreta.indexOf(caracter);
                        if (resultado == -1) {
                            incorrectos++;
                        } else {
                            if (caracter == combinacionSecreta.charAt(i)) {
                                iguales++;
                            } else {
                                distintos++;
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Hay " + iguales + " bien colocadas, " + incorrectos + " incorrectas y " +distintos+ " mal colocadas" );
                    jButtonBolaVerde.setEnabled(true);
                    jButtonBolaNaranja.setEnabled(true);
                    jButtonBolaRoja.setEnabled(true);
                    jButtonBolaAmarilla.setEnabled(true);
                    jButtonBolaTurquesa.setEnabled(true);
                    jButtonBolaAzul.setEnabled(false);
                }
                break;
             case 3:
                if (combinacionSecreta.equals(combinacionIntroducida)) {
                    JOptionPane.showMessageDialog(this, "¡¡HAS GANADO!!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    jButtonComprobar.setEnabled(false);
                    jButtonEmpezar.setEnabled(false);
                    jButtonBolaVerde.setEnabled(false);
                    jButtonBolaNaranja.setEnabled(false);
                    jButtonBolaRoja.setEnabled(false);
                    jButtonBolaAmarilla.setEnabled(false);
                    jButtonBolaTurquesa.setEnabled(false);
                    jButtonBolaAzul.setEnabled(false);
                    jLabel1.setIcon(bolaBlanca);
                    jLabel2.setIcon(bolaBlanca);
                    jLabel3.setIcon(bolaBlanca);
                    jLabel4.setIcon(bolaBlanca);
                    jLabel5.setIcon(bolaBlanca);
                    jLabel6.setIcon(bolaBlanca);
                    jLabel7.setIcon(bolaBlanca);
                    jLabel8.setIcon(bolaBlanca);
                    jLabel9.setIcon(bolaBlanca);
                    jLabel10.setIcon(bolaBlanca);
                    jLabel11.setIcon(bolaBlanca);
                    jLabel12.setIcon(bolaBlanca);
                    jLabel13.setIcon(bolaBlanca);
                    jLabel14.setIcon(bolaBlanca);
                    jLabel15.setIcon(bolaBlanca);
                    jLabel16.setIcon(bolaBlanca);
                    jLabel17.setIcon(bolaBlanca);
                    jLabel18.setIcon(bolaBlanca);
                    jLabel19.setIcon(bolaBlanca);
                    jLabel20.setIcon(bolaBlanca);
                    jLabel21.setIcon(bolaBlanca);
                    jLabel22.setIcon(bolaBlanca);
                    jLabel23.setIcon(bolaBlanca);
                    jLabel24.setIcon(bolaBlanca);
                }else{
                    for (int i = 0; i < 4; i++) {
                        char caracter = combinacionIntroducida.charAt(i);
                        int resultado = combinacionSecreta.indexOf(caracter);
                        if (resultado == -1) {
                            incorrectos++;
                        } else {
                            if (caracter == combinacionSecreta.charAt(i)) {
                                iguales++;
                            } else {
                                distintos++;
                            }
                        }
                    }
                    JOptionPane.showMessageDialog(this, "Hay " + iguales + " bien colocadas, " + incorrectos + " incorrectas y " +distintos+ " mal colocadas" );
                    jButtonBolaVerde.setEnabled(true);
                    jButtonBolaNaranja.setEnabled(true);
                    jButtonBolaRoja.setEnabled(true);
                    jButtonBolaAmarilla.setEnabled(true);
                    jButtonBolaTurquesa.setEnabled(true);
                    jButtonBolaAzul.setEnabled(true);
                }
                break;
              
        }
                
        
        System.out.println("Combinacion introducida: " + combinacionIntroducida);
        combinacionIntroducida = "";
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                
                jLabel1.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel1.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel1.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel1.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel1.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel1.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel2.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel2.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel2.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel2.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel2.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel2.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel3.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel3.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel3.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel3.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel3.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel3.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel4.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel4.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel4.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel4.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel4.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel4.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel5.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel5.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel5.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel5.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel5.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel5.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel6.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel6.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel6.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel6.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel6.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel6.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel7.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel7.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel7.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel7.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel7.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel7.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel8.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel8.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel8.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel8.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel8.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel8.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel9.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel9.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel9.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel9.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel9.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel9.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel10.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel10.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel10.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel10.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel10.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel10.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel11.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel11.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel11.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel11.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel11.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel11.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel12.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel12.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel12.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel12.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel12.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel12.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel13.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel13.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel13.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel13.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel13.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel13.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel14.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel14.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel14.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel14.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel14.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel14.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel15.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel15.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel15.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel15.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel15.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel15.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel16.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel16.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel16.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel16.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel16.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel16.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel17.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel17.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel17.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel17.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel17.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel17.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel18.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel18.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel18.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel18.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel18.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel18.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel19.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel19.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel19.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel19.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel19.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel19.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel20.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel20.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel20.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel20.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel20.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel20.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel21.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel21.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel21.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel21.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel21.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel21.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel22.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel22.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel22.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel22.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel22.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel22.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel23.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel23.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel23.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel23.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel23.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel23.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        switch(botonPulsado){
            case BOLA_VERDE:
                jLabel24.setIcon(bolaVerde);
                break;
            case BOLA_NARANJA:
                jLabel24.setIcon(bolaNaranja);
                break;
            case BOLA_ROJO:
                jLabel24.setIcon(bolaRoja);
                break;
            case BOLA_AMARILLO:
                jLabel24.setIcon(bolaAmarilla);
                break;
            case BOLA_TURQUESA:
                jLabel24.setIcon(bolaTurquesa);
                break;
            case BOLA_AZUL:
                jLabel24.setIcon(bolaAzul);
                break;
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jComboBoxNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNivelesActionPerformed
       switch(jComboBoxNiveles.getSelectedIndex()+1){
            case 1:
                jButtonEmpezar.setEnabled(true);
                jButtonBolaVerde.setEnabled(true);
                jButtonBolaNaranja.setEnabled(true);
                jButtonBolaRoja.setEnabled(true);
                jButtonBolaAmarilla.setEnabled(true);
                jButtonBolaTurquesa.setEnabled(false);
                jButtonBolaAzul.setEnabled(false);
                break;
            case 2:
                jButtonEmpezar.setEnabled(true);
                jButtonBolaVerde.setEnabled(true);
                jButtonBolaNaranja.setEnabled(true);
                jButtonBolaRoja.setEnabled(true);
                jButtonBolaAmarilla.setEnabled(true);
                jButtonBolaTurquesa.setEnabled(true);
                jButtonBolaAzul.setEnabled(false);
                break;
            case 3:
                jButtonEmpezar.setEnabled(true);
                jButtonBolaVerde.setEnabled(true);
                jButtonBolaNaranja.setEnabled(true);
                jButtonBolaRoja.setEnabled(true);
                jButtonBolaAmarilla.setEnabled(true);
                jButtonBolaTurquesa.setEnabled(true);
                jButtonBolaAzul.setEnabled(true);
                break;
            }
    }//GEN-LAST:event_jComboBoxNivelesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBolaAmarilla;
    private javax.swing.JButton jButtonBolaAzul;
    private javax.swing.JButton jButtonBolaNaranja;
    private javax.swing.JButton jButtonBolaRoja;
    private javax.swing.JButton jButtonBolaTurquesa;
    private javax.swing.JButton jButtonBolaVerde;
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JButton jButtonEmpezar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox jComboBoxNiveles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
